### ISSUE TITLE
Publish latest 1.3.2 version to Maven Central

### ISSUE THREAD

**Issue by mih-kopylov** [Steppschuh/Java-Markdown-Generator#15]
Currently latest version in Maven Central is 1.3.1.1
https://search.maven.org/artifact/net.steppschuh.markdowngenerator/markdowngenerator

Could you please publish the 0.3.2 to Maven Central as well

**Comment by Steppschuh** [comment]
Current and feature releases won't be available through Maven Central. You can get 1.3.2 from [Bintray](https://bintray.com/steppschuh/Markdown-Generator/Markdown-Generator/1.3.2) or [JitPack](https://jitpack.io/#Steppschuh/Java-Markdown-Generator/1.3.2) instead.

**Comment by mih-kopylov** [comment]
Can I know the reason why the default maven repo is not supported any more?

**Comment by Steppschuh** [comment]
Because publishing to Bintray and JitPack is much more convenient for me and I'm using this model in all my open-source libraries.

**Comment by mih-kopylov** [comment]
Excuse my integrity, but you're making an open source library not only for yourself, I believe. It's probably worth thinking about other people convenience if your goal is the lib's popularity. 

Maven Central is a default repository for Java dependencies, and adding an additional repository just for a single utility looks odd and prevents the lib's popularity.

What do you think about it?

**Comment by Steppschuh** [comment]
> you're making an open source library not only for yourself

I do, in fact, make libraries for myself. I open source them to provide value for other developers as well, in case they find it useful. Becoming popular is not one of my goals.

> It's probably worth thinking about other people convenience

I feel like the effort it takes to add the Bintray or JitPack repository is nothing compared to the effort it takes to publishing artifacts to Maven Central. Speaking from experience, as someone who has done both.

> Maven Central is a default repository for Java dependencies

Maven Central is a legacy relic of the past. The default is jcenter, the Java repository in Bintray, for [various reasons](https://stackoverflow.com/questions/24852219/android-buildscript-repositories-jcenter-vs-mavencentral). The switch has been made more than 5 years ago, and IMO there's absolutely no reason left to still use Maven Central.

**Comment by mih-kopylov** [comment]
Okay, I got your point. Thanks for detailed explanation! :)
