### ISSUE TITLE
OSGI Manifest

### ISSUE THREAD

**Issue by ChristianHoesel** [Steppschuh/Java-Markdown-Generator#17]
Please provide an artifact with an OSGI Manifest using Gradle BND Plugin (https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.gradle/README.md).

Thank you!

**Comment by Steppschuh** [comment]
I won't do this as I don't think it's worth the effort. If you feel like working on it, please create a PR and I'll consider merging it.
