### ISSUE TITLE
Combine effort

### ISSUE THREAD

**Issue by RobWin** [Steppschuh/Java-Markdown-Generator#2]
What do you think about joining forces and working together on an Markup builder library?
We have developed this library https://github.com/Swagger2Markup/markup-document-builder which is used by https://github.com/Swagger2Markup/swagger2markup
The library has many more features than shown in the Readme.

**Comment by Steppschuh** [comment]
Hey Rob,
thanks for the heads up. I'll continue working on this library, even though it's not as mature as your markup builder yet, because it's already part of many internal projects.
