### ISSUE TITLE
CodeBlock doesn't use system line separator

### ISSUE THREAD

**Issue by Qworel97** [Steppschuh/Java-Markdown-Generator#21]
```java
@Override
    public String getSuccessor() {
        return "\n```";
    }
```

In Table System.lineSeparator() is used, why not use it here also?

**Comment by Qworel97** [comment]
Created [pull request](https://github.com/Steppschuh/Java-Markdown-Generator/pull/23)

**Comment by Qworel97** [comment]
@Steppschuh is there any plans for publishing new version in maven central?

**Comment by Steppschuh** [comment]
No, please refer to #15.

You can however get a release with your changes using:

```gradle
repositories {
    maven { url 'https://jitpack.io' }
}
dependencies {
    compile 'com.github.Steppschuh:Java-Markdown-Generator:master-SNAPSHOT'
}
```
