### ISSUE TITLE
Use System.lineSeperator instead of "\n" for platform independence

### ISSUE THREAD

**Issue by sandrozbinden** [Steppschuh/Java-Markdown-Generator#7]
I got failing unit tests on windows platform as the current implementation use hardcoded "\n" new line for line seperation. It would be great to replace those with the platform indepentent System.lineSeperator in order to get "\n" for unix and "\r\n" for windows systems.

The following files would needed to be changed

java/net/steppschuh/markdowngenerator/list/UnorderedList.java
java/net/steppschuh/markdowngenerator/table/Table.java
java/net/steppschuh/markdowngenerator/text/code/CodeBlock.java
java/net/steppschuh/markdowngenerator/text/heading/Heading.java
java/net/steppschuh/markdowngenerator/text/quote/Quote.java
java/net/steppschuh/markdowngenerator/text/HeadingTest.java

**Comment by Steppschuh** [comment]
Thanks for reporting, you're right. Please feel free to submit a PR, I won't be able to work on this in the next few days.

**Comment by sandrozbinden** [comment]
Hi @Steppschuh. Thanks for your reply. I created a new PR with the changes.
